WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WhiskeyTangoFoxtrot.Models;
using WhiskeyTangoFoxtrot.Models.Viewmodels;
using WhiskeyTangoFoxtrot.DAL;
using WhiskeyTangoFoxtrot.Repositories.Interfaces;
using WhiskeyTangoFoxtrot.Repositories.Persistance;
using WhiskeyTangoFoxtrot.Repositories;


namespace WhiskeyTangoFoxtrot.Controllers
{
    public class ForumController : Controller
    {
        private WTFContext db = new WTFContext();

        private UnitOfWork unitOfWork = new UnitOfWork(new WTFContext());

        private IForumPostRepository _forumPost;
        private IForumsRepository _forum;
        private IWTFUserRepository _user;


        public ForumController() { }

        public ForumController(IForumsRepository forums, IForumPostRepository forumPostRepository, IWTFUserRepository wTFUser)
        {
            _forum = forums;
            _forumPost = forumPostRepository;
            _user = wTFUser;
        }

        public ForumController(IForumPostRepository MOCKforumPostRepository)
        {
            _forumPost = MOCKforumPostRepository;

        }

        // GET: Forum
        public ActionResult Index()
        {
            var viewmodel = CreateViewModel();
            return View(viewmodel);
        }

        // GET: Forum/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var viewmodel = CreateViewModel(id);
            Forum forum = unitOfWork.Forums.Get(id);
            if (forum == null)
            {
                return HttpNotFound();
            }
            /*
            if (forum.IsActive != null && GetUserID() != unitOfWork.Forums.Forums.Select(a => a.WTFUserID).FirstOrDefault())
            {
                return Redirect("~/WTFErrors/Error.html");
            }
            */
            viewmodel.Forums.Select(a => a.ForumID == forum.ForumID).FirstOrDefault();
            return View(viewmodel);
        }

        // GET: Forum/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.WTFUserID = new SelectList(db.WTFUsers, "WTFUserID", "Username");
            return View();
        }

        // POST: Forum/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ForumName,Message,IsActive,IsMemberOnly")] Forum forum)
        {
            forum.ForumID = db.Fora.Count() + 1;
            forum.WTFUserID = GetUserID();
            if (ModelState.IsValid)
            {
                db.Fora.Add(forum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.WTFUserID = new SelectList(db.WTFUsers, "WTFUserID", "Username", forum.WTFUserID);
            return View(forum);
        }

        // GET: Forum/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Forum forum = unitOfWork.Forums.Get((int)id);
            if (forum == null)
            {
                return HttpNotFound();
            }

            var user = GetUserID();
            if (forum.WTFUserID != user)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.WTFUserID = new SelectList(unitOfWork.WTFUser.GetAll(), "WTFUserID", "Username", forum.WTFUserID);
            return View(forum);
        }

        // POST: Forum/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ForumID,WTFUserID,ForumName,Message,IsActive,IsMemberOnly")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Forums.SetModified(forum);
                unitOfWork.Complete();

                /*
                db.Entry(forum).State = EntityState.Modified;
                db.SaveChanges();
                */
                return RedirectToAction("Index");
            }
            ViewBag.WTFUserID = new SelectList(unitOfWork.WTFUser.GetAll(), "WTFUserID", "Username", forum.WTFUserID);
            return View(forum);
        }

        // GET: Forum/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Forum forum = unitOfWork.Forums.Get((int)id);
            if (forum == null)
            {
                return HttpNotFound();
            }
            var userID = GetUserID();

            if (userID != forum.WTFUserID)
            {
                return new HttpUnauthorizedResult();
            }
            return View(forum);
        }

        // POST: Forum/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Forum forum = unitOfWork.Forums.Get(id);
            unitOfWork.Forums.Remove(forum);
            unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        private ForumViewModel CreateViewModel(int? forumID)
        {

            //int UserID = GetUserID();

            ForumViewModel forumViewModel = new ForumViewModel
            {
                WTFUsers = unitOfWork.WTFUser.GetAll(),

                ForumPost = unitOfWork.Posts.GetAll().Where(a => a.ForumID == forumID),

                Forums = unitOfWork.Forums.Find(a => a.ForumID == forumID)
            };

            return forumViewModel;
        }

        [Authorize]
        private ForumViewModel CreateViewModel()
        {

            //int UserID = GetUserID();

            ForumViewModel forumViewModel = new ForumViewModel
            {
                WTFUsers = unitOfWork.WTFUser.GetAll(),

                ForumPost = unitOfWork.Posts.GetAll(),

                Forums = unitOfWork.Forums.GetAll()
            };

            return forumViewModel;
        }

        [Authorize]
        private int GetUserID()
        {
            string user1 = User.Identity.GetUserId();

            WTFUser user = db.WTFUsers.Where(a => a.AspNetIdentityID == user1).FirstOrDefault();
            
            int UserID = user.WTFUserID;

            return UserID;
        }

        [Authorize]
        [HttpPost]
        public ActionResult replyTo(int postingID, string replyString)//int postingID, string replyString)
        {
            //var forumID = db.ForumPosts.Where(b => b.ForumPostID == postingID).Select(a => a.ForumID).FirstOrDefault();
            var forumID = unitOfWork.Posts.Get(postingID).ForumID;

            //ForumPost forumPost = db.ForumPosts.Create();
            ForumPost forumPost = new ForumPost();
            forumPost.ForumPostID = getNextIndex();
            forumPost.ForumID = forumID;
            forumPost.WTFUserID = GetUserID();
            forumPost.ReplyID = postingID;
            forumPost.PostMessage = replyString;

            if (ModelState.IsValid)
            {
                //   db.ForumPosts.Add(forumPost);
                //  db.SaveChanges();
                unitOfWork.Posts.Get(postingID).Replies += 1;
                unitOfWork.Posts.Add(forumPost);
                unitOfWork.Complete();

                replyAlert();
                return View(Details(forumID));

            }
            else
            {
                return RedirectToAction("Index");
            }

        }

        public int getNextIndex()
        {
            //int index = db.ForumPosts.Count() + 1;
            int index = unitOfWork.Posts.GetAll().Count() + 1;
            return index;
        }

        public int getNextIndex(int[] arr)
        {
            int index = arr.Count() + 1;

            return index;
        }
        [Authorize]
        [HttpPost]
        public ActionResult replyToMain(int forumid, string replyString)
        {
            var forumID = db.Fora.Where(b => b.ForumID == forumid).Select(a => a.ForumID).FirstOrDefault();

            ForumPost forumPost = db.ForumPosts.Create();
            forumPost.ForumPostID = db.ForumPosts.Count() + 1;
            forumPost.ForumID = forumID;
            forumPost.WTFUserID = GetUserID();
            forumPost.ReplyID = null;
            forumPost.PostMessage = replyString;

            if (ModelState.IsValid)
            {
                db.ForumPosts.Add(forumPost);
                db.SaveChanges();
                return View(Details(forumID));

            }
            else
            {
                return RedirectToAction("Index");
            }

        }

        [Authorize]
        public void replyAlert()
        {

        }
    }
}

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WhiskeyTangoFoxtrot.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Mission()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult UnderConstruction()
        {
            return View();
        }

        public ViewResult FaqPage()
        {
            return View();
        }

        [HttpGet]
        public ActionResult MessageBoard()
        {
            var chatUser = "";

            chatUser = HttpContext.User.Identity.Name.ToString();
            ViewBag.chatUser = chatUser;

            return View();
        }
    }
}

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Controllers/VAFacilitySearchController.cs
using System.Diagnostics;
using System.IO;
using System.Net;
using WhiskeyTangoFoxtrot.Models;
using System.Web.Mvc;
using System.Linq;
using WhiskeyTangoFoxtrot.DAL;
using WhiskeyTangoFoxtrot.Repositories.Interfaces;
using System.Data.Entity;

namespace WhiskeyTangoFoxtrot.Controllers
{
    public class VAFacilitySearchController : Controller
    {
        readonly string key = System.Web.Configuration.WebConfigurationManager.AppSettings["apiKey"];

        private WTFContext db = new WTFContext();

        // For Testing
        public VAFacilitySearchController()
        {
        }

        private ICityRepository _city;
        
        public VAFacilitySearchController(ICityRepository _city)
        {
            this._city = _city;
        }

        // Search for VA Facilties view page
        public ActionResult Search()
        {
            return View(db.Cities.ToList());
        }
        
        /// <summary>
        /// Main work horse of the controller, constructs a bounding box, embeds api key in the header of the html request,
        /// and returns a json result of all the data for facilities in the area of the bounding box.
        /// </summary>
        /// <param name="lat">User submitted latitude</param>
        /// <param name="lon">User submitted longitude</param>
        /// <returns>JSON array with VA facility information</returns>
        [HttpGet]
        public JsonResult FacilitySearch(decimal? lat, decimal? lon)
        {
            // Send latitude and longitude to the helper method to construct the array
            decimal?[] box = FacilitySearchHelper(lat, lon);

            // example query string formats, by BBOX and by ID using BBOX for application currently
            //Error Code 400 means inproper query string
            //<https://dev-api.va.gov/services/va_facilities/v0/facilities?bbox%5B%5D=-120&bbox%5B%5D=40&bbox%5B%5D=-125&bbox%5B%5D=50>
            //string qurl = "https://dev-api.va.gov/services/va_facilities/v0/facilities/?" + "ids=vha_668";

            // String constructed from the bounding box
            string qurl = "https://dev-api.va.gov/services/va_facilities/v0/facilities/?bbox%5B%5D=" 
                + box[0] + "&bbox%5B%5D=" + box[1] + "&bbox%5B%5D=" + box[2] + "&bbox%5B%5D=" + box[3];

            // Build the api request with added key in header
            WebRequest request = WebRequest.Create(qurl);
            request.Headers["apiKey"] = key;

            // Open the response and get the data
            WebResponse response = request.GetResponse();
            Stream stream = response.GetResponseStream();
            string reader = new StreamReader(stream).ReadToEnd();

            // Make it usable 
            var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            var data = serializer.DeserializeObject(reader);

            // Clean up
            stream.Close();
            response.Close();

            // Return with the data, list of VA facilities
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        // Build the array used for the bounding box based on lat/long provided
        public decimal?[] FacilitySearchHelper(decimal? lat, decimal? lon)
        {
            // Grab the two longitude parameters for the box
            decimal? a1 = lon + (decimal)0.5;
            decimal? a2 = lon - (decimal)0.5;

            // Grab the two latitude parameters for the box
            decimal? b1 = lat + (decimal)0.5;
            decimal? b2 = lat - (decimal)0.5;

            // Fill the box with an order of a1,b1,a2,b2 (long/lat, long/lat)
            decimal?[] box = new decimal?[4];
            box[0] = a1;
            box[1] = b1;
            box[2] = a2;
            box[3] = b2;

            // Return the bounding box coordinates
            return box;
        }
    }
}

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2 style="text-align:center">@ViewBag.Title</h2>

<p style="text-align:center">
    We would love to hear from you! If you have any suggestions, comments, or concerns, please contact us at: <strong>whiskey.tango.foxtrot.site@gmail.com</strong>
</p>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/FaqPage.cshtml
@{
    ViewBag.Title = "FAQ";
}

<div id="main_div_faq">
    <div id="faq_page">
        <h1>@ViewBag.Title</h1>
        <h2>We are here to help you!</h2>
    </div>
    <div class="row" id="faq_page_questions">
        <div class="col-md-12" id="faq_search_div">
            <div class="form-inline" id="faq_textbox">
                @using (Html.BeginForm())
                {
                    @Html.TextBox("faq_search", null, new { @class = "form-control", style = "width: 800px;", placeholder = "Search for answers" })
                    <span><input type="submit" class="btn btn-primary" value="Search" /></span>
                }
            </div>
        </div>
    </div>
    <div class="row" id="row_faq">
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Using the Facility Finder</p>
                            @Html.ActionLink("Facility Questions", "FacilityFinder", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Facility Cleanliness</p>
                            @Html.ActionLink("Is the Facility Clean?", "Cleanliness", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Account Inqueries</p>
                            @Html.ActionLink("Account Questions", "Inqueries", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Discussion Page Questions</p>
                            @Html.ActionLink("Questions About Discussions", "Discussion", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Live Chat Assistance</p>
                            @Html.ActionLink("Live Chat Questions", "LiveChat", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="faq_card_size">
                <div class="card faq-page">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text">Future Services Offered</p>
                            @Html.ActionLink("Future Service Questios", "Future", "FAQ")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link rel="stylesheet" type="text/css" href="~/Content/CSS/Site.css" />

@*Index page container that holds image and transbox*@
<div class="container-fluid">
    <div class="col-lg-12" id="main_head_div">
        <h1 id="main_h1">Whiskey Tango Foxtrot</h1>
        @*The transbox which holds information about the site; located within image*@
        <div class="transbox">
            <p class="main_paragraph">
                Welcome to Whiskey Tango Foxtrot!
                Our site is designed to be a place for military personnel and their families to search for VA facilities, discuss topics of interest,
                and live chat with others. We want our site to be easy to use and give our service men and women a place where they can get needed value all
                in one spot.
            </p>
            <p class="main_paragraph">
                This site is just coming into its own, meaning that we would like to add features a little at a time that will bring greater value to our
                military veterans which will include ways to check your benefits, schedule appointments, and anything else that would make getting things
                accomplished in a more streamlined manner. You've dedicated your life to your country, and we believe you need an easier way to navigate life
                and keep it uncomplicated to find the services and help you need.
            </p>
            <p class="main_paragraph">
                Currently, we offer limited services, but with your help, our goal is to create a site that is what our military personel want, so please use
                our contact page to send us a message of the services you would find beneficial to you. We have our ears open and look forward to hearing from
                you. Thank you for your service and dedication.
            </p>
        </div>
    </div>
</div>
@*Section of index which contains cards with links to specific areas within the site; cards used for future features can be added in this area*@

<div class="row">
    <div class="card-deck">
        <div class="col-md-4">
            <div class="card">
                @*Card for VA facility search*@
                <img class="card-img-top" src="~/Content/images/map.jpg" alt="Map image" />
                <div class="card-body">
                    <h3>Find a VA Facility</h3>
                    <p>
                        We can help you find a local VA facility, or if you are traveling and want to find a facility to where you will be staying,
                        you can also access that information. The information provided will include the name of the facility, its address and telephone
                        number, and the hours of operation.
                    </p>
                    <p style="text-align:center">
                        <input type="button" class="btn btn-primary btn-sm" value="Find A Facility" onclick="location.href='@Url.Action("Search", "VAFacilitySearch")'" />
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                @*Card for discussion page; can be changed to link to forums page*@
                <img class="card-img-top" src="~/Content/images/soldieroncomputer.jpg" alt="Soldier on computer" />
                <div class="card-body">
                    <h3>Start a Discussion</h3>
                    <p>
                        We offer a discussion page where you can find what other military people are talking about. At times, you may need
                        information about the conditions of a VA facility in your area or how people are treated at a certain location. This is
                        a great place to start. Unfortunately, our discussion page is for site account holders so we can control any false information
                        from being spread.
                    </p>
                    <p style="text-align:center">
                        <input type="button" class="btn btn-primary btn-sm" value="View Forums" onclick="location.href='@Url.Action("Index", "Forum")'" />
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                @*Card to link to live chat page; the link triggers a modal popup to prompt the user to log in or use an anonymous name to use the
                    chat feature*@
                <img class="card-img-top" src="~/Content/images/livechat.jpg" alt="Live chat emblem" />
                <div class="card-body">
                    <h3>Live Chat with a Friend</h3>
                    <p>
                        Sometimes as people, we just need to reach out to loved ones or others for advice or a shoulder to lean on. With our live
                        chat, we want to help you with this valuable resource. Find those people that can give you the comfort you need when you
                        need it.
                    </p>
                    <p style="text-align:center">
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#target_modal">Live Chat</button>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="answer"></div>
@*Modal popup for user choice of logging in or to be given a random 'anon' name; cancel button just leaves user on index page*@
<div class="modal fade" id="target_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            @*Header section which is used to close the modal window*@
            <div class="modal-header">
                <h5 class="modal-title">Close Window</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @*Body section which contains information for the user to select log in or 'anon' name*@
            <div class="modal-body">
                <p>
                    In order to use the live chat, you will need to provide a name.
                    Would you like to log in or use an anonymous name?
                </p>
            </div>
            @*Footer section with buttons for user selection*@
            <div class="modal-footer">
                @*This button redirects the user to the log in page*@
                <form action="/Account/Login" method="get">
                    <button type="submit" class="btn btn-warning" id="login_btn" onclick="getBtnEventLogin()">Log In</button>
                </form>
                @*This button redirects the user to the live chat page*@
                <form action="/Home/MessageBoard" method="get">
                    <button type="submit" class="btn btn-warning" id="lc_btn">Anonymous</button>
                </form>
                @*This button stays on the index page; no redirect*@
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/MessageBoard.cshtml
@{
    ViewBag.Title = "MessageBoard";
}

<h2 id="chat_h2">Live Chat</h2>

@*Main div to hold page elements*@
<div id="chat_div_main">
    @*Welcome div to display Welcome with user's name; including anon names*@
    <div class="col-4" id="welcome_spot">
        Welcome @ViewBag.chatUser
    </div>
    @*Chat box div*@
    <div class="container-fluid">
        <div class="row">
            <div class="chat-panel panel panel-default" id="chatbox_div">
                @*Panel heading*@
                <div class="panel-heading" id="chatbox_header">
                    Chat Box
                    <i class="fa fa-paper-plane fa-fw"></i>
                </div>
                @*Panel body*@
                <div class="panel-body" >
                    <div class="chat_body" id="chat">
                        @*displayname holds the username for the live chat*@
                        <input type="hidden" id="displayname" />
                        <div class="chat_message" id="discussion"></div>
                        <audio src="~/Content/Audio/MsgNudge.wav" autostart="true" id="audio" />
                    </div>
                </div>
                @*Panel footer*@
                <div class="panel-footer">
                    <div class="input-group">
                        @*Textbox for writing messages to post*@
                        <input type="text" id="message" class="form-control" placeholder="Enter your message here..." />
                        <span class="input-group-btn">
                            @*Button to post message*@
                            <button id="sendmessage" type="button" class="btn btn-primary btn-sm" >Send</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="chatbox_footer">
        <p class="lead">
            To use the chat box, enter your message in the prompted area at the bottom of the chat area and click on the button to
            send your message. Your message will appear on the right-hand side of the chat area and replies will be on the left-hand
            side.
        </p>
        <p class="lead">
            Thank you for using our chat service!
        </p>
    </div>
</div>

@section scripts {
    @*Reference JQuery library*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @*Reference SignalR library*@
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    @*Reference auto-generated SignalR hub script --WILL NOT BE FOUND! SIGNALR USES THIS--*@
    <script src="~/signalr/hubs"></script>
    @*Add MyScripts.js file with function to run chat box*@
    <script src="~/Scripts/MyScripts.js" type="text/javascript"></script>
}

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/Mission.cshtml
@{
    ViewBag.Title = "Our Mission";
}
<h2>@ViewBag.Title.</h2>

<div class="col-lg-12">
    <p class="lead">
            Our mission is to provide our dedicated service men, women, and their families a way to access services to make life a little easier.
            We believe that by creating a website that allows an easy way to find VA facilities, have discussions, and to live chat were important
            services for our veterans.
        </p>
        <p class="lead">
            Currently, we have not found another website that offers multiple services that would provide an all-in-one platform where a veteran or
            family member can go to receive information such as looking for a VA facility and finding out through a discussion board what type of
            services are offered at the facility or what the customer service was like when someone else visited that facility. With our site, you
            will have this type of access to that information.
        </p>
        <p class="lead">
            This website is a work in progress meaning we envision more services offered later on which will include checking benefits, making
            appointments at a specific facility, and requesting Uber or Lyft transportation to a scheduled appointment. Please visit our contact page
            and feel free to send us an email telling us what services you would like to see added to the site. We are building this for you and want
            your experience on our website to be stress free.
        </p>
        <p class="lead">
            All of us at Drunken Coders would like to thank each and every one of you for your dedication and service to our country!
        </p>
        <p><strong>THANK YOU!</strong></p>
</div>

WhiskeyTangoFoxtrot/WhiskeyTangoFoxtrot/Views/Home/UnderConstruction.cshtml
@{
    ViewBag.Title = "Under Construction";
}

<h2>Don't fret, the page is incoming shortly.</h2>